package vetor;

import static org.junit.Assert.fail;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;


public class VetorTest {

    private Vetor<Integer> vetor;
    @Before
    public void setUp() throws Exception {
        this.vetor = new Vetor<Integer>(5);
    }

    @Test
    public void testInserir() {
        vetor.inserir(1);
        Assert.assertEquals(new Integer(1), vetor.procurar(1));
        
        vetor.inserir(2);
        Assert.assertEquals(new Integer(2), vetor.procurar(2));

        vetor.inserir(3);
        Assert.assertEquals(new Integer(3), vetor.procurar(3));

        vetor.inserir(4);
        Assert.assertEquals(new Integer(4), vetor.procurar(4));

        vetor.inserir(5);
        Assert.assertEquals(new Integer(5), vetor.procurar(5));

        try {
            vetor.inserir(10);
        }catch (Exception erro) {
            Assert.assertEquals("5", erro.getMessage());
        }
        
    }

    @Test
    public void testRemover() {
        fail("Not yet implemented");
    }

    @Test
    public void testProcurar() {
        fail("Not yet implemented");
    }

    @Test
    public void testIsVazio() {
        fail("Not yet implemented");
    }

    @Test
    public void testIsCheio() {
        fail("Not yet implemented");
    }

}
